version: 2
jobs:
  build:
    docker:
      - image: keyclipse/docker_deploy
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Docker Login
          command: docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Build Docker 
          command: docker build -t keyclipse/react-redux-ifgfseattle:${CIRCLE_SHA1} .
      - run:
          name: Push Docker
          command: docker push keyclipse/react-redux-ifgfseattle:${CIRCLE_SHA1}
      - run:
          name: Kops export
          command: kops export kubecfg --name ifgftest.curchats.com --state s3://ifgfkopstest
      - run:
          name: Kubernetes deployment
          command: kubectl set image deployment/ifgf-deployment frontend=keyclipse/react-redux-ifgfseattle:${CIRCLE_BUILD_NUM}

      
