version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: circleci/node:7.10
    steps:
      - run:
          name: Trigger Kubernetes Deploy
          command: git clone https://github.com/sdkitono/react-redux-ifgfseattle && git clone https://github.com/sdkitono/ifgf-backend

