version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: keyclipse/docker_deploy
    steps:
      - run:
          name: Trigger Kubernetes Deploy
          command: git clone https://github.com/sdkitono/react-redux-ifgfseattle && git clone https://github.com/sdkitono/ifgf-backend

